/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminAuthRouteImport } from './routes/admin-auth'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminTicketsRouteImport } from './routes/admin/tickets'
import { Route as AdminMapRouteImport } from './routes/admin/map'
import { Route as AdminDatabaseRouteImport } from './routes/admin/database'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AuthenticatedWeatherRouteImport } from './routes/_authenticated/weather'
import { Route as AuthenticatedTicketsRouteImport } from './routes/_authenticated/tickets'
import { Route as AuthenticatedSensorsRouteImport } from './routes/_authenticated/sensors'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedMarketplaceRouteImport } from './routes/_authenticated/marketplace'
import { Route as AuthenticatedIrrigationRouteImport } from './routes/_authenticated/irrigation'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedFarmRouteImport } from './routes/_authenticated/farm'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAssistantRouteImport } from './routes/_authenticated/assistant'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthRoute = AdminAuthRouteImport.update({
  id: '/admin-auth',
  path: '/admin-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTicketsRoute = AdminTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMapRoute = AdminMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDatabaseRoute = AdminDatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthenticatedWeatherRoute = AuthenticatedWeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTicketsRoute = AuthenticatedTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSensorsRoute = AuthenticatedSensorsRouteImport.update({
  id: '/sensors',
  path: '/sensors',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketplaceRoute =
  AuthenticatedMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIrrigationRoute = AuthenticatedIrrigationRouteImport.update({
  id: '/irrigation',
  path: '/irrigation',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFarmRoute = AuthenticatedFarmRouteImport.update({
  id: '/farm',
  path: '/farm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssistantRoute = AuthenticatedAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin-auth': typeof AdminAuthRoute
  '/auth': typeof AuthRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/farm': typeof AuthenticatedFarmRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/irrigation': typeof AuthenticatedIrrigationRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sensors': typeof AuthenticatedSensorsRoute
  '/tickets': typeof AuthenticatedTicketsRoute
  '/weather': typeof AuthenticatedWeatherRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/database': typeof AdminDatabaseRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/users': typeof AdminUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin-auth': typeof AdminAuthRoute
  '/auth': typeof AuthRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/farm': typeof AuthenticatedFarmRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/irrigation': typeof AuthenticatedIrrigationRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sensors': typeof AuthenticatedSensorsRoute
  '/tickets': typeof AuthenticatedTicketsRoute
  '/weather': typeof AuthenticatedWeatherRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/database': typeof AdminDatabaseRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/users': typeof AdminUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin-auth': typeof AdminAuthRoute
  '/auth': typeof AuthRoute
  '/_authenticated/assistant': typeof AuthenticatedAssistantRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/farm': typeof AuthenticatedFarmRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRoute
  '/_authenticated/irrigation': typeof AuthenticatedIrrigationRoute
  '/_authenticated/marketplace': typeof AuthenticatedMarketplaceRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/sensors': typeof AuthenticatedSensorsRoute
  '/_authenticated/tickets': typeof AuthenticatedTicketsRoute
  '/_authenticated/weather': typeof AuthenticatedWeatherRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/database': typeof AdminDatabaseRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/users': typeof AdminUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-auth'
    | '/auth'
    | '/assistant'
    | '/dashboard'
    | '/farm'
    | '/finance'
    | '/irrigation'
    | '/marketplace'
    | '/profile'
    | '/reports'
    | '/sensors'
    | '/tickets'
    | '/weather'
    | '/admin/dashboard'
    | '/admin/database'
    | '/admin/map'
    | '/admin/tickets'
    | '/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-auth'
    | '/auth'
    | '/assistant'
    | '/dashboard'
    | '/farm'
    | '/finance'
    | '/irrigation'
    | '/marketplace'
    | '/profile'
    | '/reports'
    | '/sensors'
    | '/tickets'
    | '/weather'
    | '/admin/dashboard'
    | '/admin/database'
    | '/admin/map'
    | '/admin/tickets'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/admin-auth'
    | '/auth'
    | '/_authenticated/assistant'
    | '/_authenticated/dashboard'
    | '/_authenticated/farm'
    | '/_authenticated/finance'
    | '/_authenticated/irrigation'
    | '/_authenticated/marketplace'
    | '/_authenticated/profile'
    | '/_authenticated/reports'
    | '/_authenticated/sensors'
    | '/_authenticated/tickets'
    | '/_authenticated/weather'
    | '/admin/dashboard'
    | '/admin/database'
    | '/admin/map'
    | '/admin/tickets'
    | '/admin/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AdminAuthRoute: typeof AdminAuthRoute
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-auth': {
      id: '/admin-auth'
      path: '/admin-auth'
      fullPath: '/admin-auth'
      preLoaderRoute: typeof AdminAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/tickets': {
      id: '/admin/tickets'
      path: '/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AdminTicketsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/map': {
      id: '/admin/map'
      path: '/map'
      fullPath: '/admin/map'
      preLoaderRoute: typeof AdminMapRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/database': {
      id: '/admin/database'
      path: '/database'
      fullPath: '/admin/database'
      preLoaderRoute: typeof AdminDatabaseRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authenticated/weather': {
      id: '/_authenticated/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof AuthenticatedWeatherRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tickets': {
      id: '/_authenticated/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AuthenticatedTicketsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sensors': {
      id: '/_authenticated/sensors'
      path: '/sensors'
      fullPath: '/sensors'
      preLoaderRoute: typeof AuthenticatedSensorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketplace': {
      id: '/_authenticated/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AuthenticatedMarketplaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/irrigation': {
      id: '/_authenticated/irrigation'
      path: '/irrigation'
      fullPath: '/irrigation'
      preLoaderRoute: typeof AuthenticatedIrrigationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/farm': {
      id: '/_authenticated/farm'
      path: '/farm'
      fullPath: '/farm'
      preLoaderRoute: typeof AuthenticatedFarmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistant': {
      id: '/_authenticated/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthenticatedAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAssistantRoute: typeof AuthenticatedAssistantRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFarmRoute: typeof AuthenticatedFarmRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRoute
  AuthenticatedIrrigationRoute: typeof AuthenticatedIrrigationRoute
  AuthenticatedMarketplaceRoute: typeof AuthenticatedMarketplaceRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSensorsRoute: typeof AuthenticatedSensorsRoute
  AuthenticatedTicketsRoute: typeof AuthenticatedTicketsRoute
  AuthenticatedWeatherRoute: typeof AuthenticatedWeatherRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAssistantRoute: AuthenticatedAssistantRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFarmRoute: AuthenticatedFarmRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRoute,
  AuthenticatedIrrigationRoute: AuthenticatedIrrigationRoute,
  AuthenticatedMarketplaceRoute: AuthenticatedMarketplaceRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSensorsRoute: AuthenticatedSensorsRoute,
  AuthenticatedTicketsRoute: AuthenticatedTicketsRoute,
  AuthenticatedWeatherRoute: AuthenticatedWeatherRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDatabaseRoute: typeof AdminDatabaseRoute
  AdminMapRoute: typeof AdminMapRoute
  AdminTicketsRoute: typeof AdminTicketsRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDatabaseRoute: AdminDatabaseRoute,
  AdminMapRoute: AdminMapRoute,
  AdminTicketsRoute: AdminTicketsRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AdminAuthRoute: AdminAuthRoute,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
